COMPANY: 
        - "AAPL"
        - "NVDA"
        - "AMD"
        - "GOOGL"
        - "VOD"
        - "9432.T"
        - "9997.T"
START_DAY: "2023-01-01"
END_DAY: "2026-03-10"
STL_TARGET: "High"
PRED_TARGET: "y"
PRED_FEATURE: "ds"
AVERAGE: "yhat"
AVERAGE_UPPER: "yhat_upper"
AVERAGE_LOWER: "yhat_lower"
PERIOD: 24
RENAME_COLUMNS:
        Date: "ds"
        High: "y"
